POST http://localhost:4004/auth/register
Content-Type: application/json

{
  "firstName": "asdAliasdzxc",
  "lastName": "Bsadoualiasd",
  "email": "ali2@mail.com",
  "password": "pAssword12!_",
  "cofirmPassword": "pAssword12!_",
  "phoneNumber": "+4912389765654"
}